version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    networks:
      - appnet
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
