blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/Vikashrock45/TidySnips/discussions
    about: Ask questions, share ideas, and discuss TidySnips with the community
  - name: 📖 Documentation
    url: https://github.com/Vikashrock45/TidySnips#readme
    about: Check our comprehensive documentation for guides and API references
  - name: 🔒 Security Issues
    url: https://github.com/Vikashrock45/TidySnips/security/advisories/new
    about: Report security vulnerabilities privately (recommended for critical issues)
